language: python

matrix:
  fast_finish: true
  allow_failures:
    - python: nightly
    - python: 3.7-dev
    - python: 3.6-dev

python:
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - nightly

script:
  - coverage run -m unittest test

after_success:
  - coveralls
